apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
  namespace: {{.Values.nameSpace}}
spec:
  type: {{.Values.service.serviceType}}
  selector:
    app: {{.Values.appName}}
  ports:
  - protocol: TCP
    port: {{.Values.service.servicePort}}
    targetPort: {{.Values.containerPort}}