apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.appName}}
  namespace: {{.Values.nameSpace}}
  
# provide mysql root password
type: Opaque
data:
  mysql-root-password: {{.Values.secret.mysqlRootPass}}
